############# 카메라 캡쳐 #############
camera:
  width: 640
  height: 480
  fps: 30
queue: 4

############# 영상 개선 기능 #############
preprocessing:
  preset: Night

# 수동 커스텀도 그대로 지원
# preprocessing:
#   contrast_enhance:
#     gamma: 0.75
#   edge_enhance:
#     ksize: 5
#     amount: 1.0

############# 모델 추론 #############
det_model: ../../models/tf2_ssd_mobilenet_v2_coco17_ptq_edgetpu.tflite
det_thresh: 0.7