source: 0  # Camera ID (0) or video path string

############# 카메라 캡쳐 #############
camera:
  width: 640
  height: 480
  fps: 30

############# 영상 개선 기능 #############
preprocessing:
  Contrast:
    enable: true
    value1: 1.5
    value2: 4
  EdgeEnhance:
    enable: true
    value: 1.0
  Denoise:
    enable: false
    value1: 1.0
    value2: 0
  Deblur:
    enable: false
  Clutter:
    enable: false

############# 모델 추론 #############
detector:
  model: models/tf2_ssd_mobilenet_v2_coco17_ptq_edgetpu.tflite
  threshold: 0.7

############# 모델 추적 #############
tracker:
  name: sort
  params:
    max_age: 30
    min_hits: 3
    iou_threshold: 0.3

############# 영상 출력 #############
display_gray: false
